### ISSUE TITLE
No repose from UPI intent once user pay successfully

### ISSUE THREAD

**Issue by prabusharan** [ArunYogi/cordova-plugin-upi#1]
Most of the time response comes under failure callback. major issues phonepe UPI still not provide response result in both success or failure callback case.

**Comment by prabusharan** [comment]
1) How can we restrict UPI applications in this plugin?
2) Did you test major UPI in Google Pay, Phonepe, Paytm and BHIM?
 In google pay response in failure callback for both success and failure transaction.
 In Phonepe response no response callback for both success and failure transaction.

**Comment by vishwanath-ca** [comment]
@ArunYogi I have provided fix for UPI Payments null response. Please check the PR
@prabusharan - Once @ArunYogi accepts the PR - you can update the dependency. It should work fine for UPI payments.

**Comment by vishwanath-ca** [comment]
@prabusharan have you tried?
window["UPI"].acceptPayment(config, null, successCallback, failureCallback);
@ArunYogi please confirm if this is how it should be used? I see some gap between the documentation and the code.

**Comment by ArunYogi** [comment]
> @prabusharan have you tried?
> window["UPI"].acceptPayment(config, null, successCallback, failureCallback);
> @ArunYogi please confirm if this is how it should be used? I see some gap between the documentation and the code.

window["UPI"].acceptPayment(config, null, successCallback, failureCallback); // this is also a way to call. In this way, plugin will show all UPI supporting apps and proceeds further. If you want reach out particular upi supported app, then you should pass that app information as 2nd param to the same method.

**Comment by ArunYogi** [comment]
> @ArunYogi I have provided fix for UPI Payments null response. Please check the PR
> @prabusharan - Once @ArunYogi accepts the PR - you can update the dependency. It should work fine for UPI payments.

I have merged the pull request and published a new version 1.0.2. Please check it

**Comment by vishwanath-ca** [comment]
Thank you @ArunYogi

**Comment by vishwanath-ca** [comment]
Can this be closed? Or is there anything still pending?
