### ISSUE TITLE
 parseUpiResponse(intent.getStringExtra("response"), result); throws error

### ISSUE THREAD

**Issue by mtech2008** [ArunYogi/cordova-plugin-upi#6]
Unable to get SUCCESS or FAILURE response as I found during debug   parseUpiResponse(intent.getStringExtra("response"), result); throws error.

**Comment by vishwanath-ca** [comment]
Fixed in https://github.com/ArunYogi/cordova-plugin-upi/pull/10

**Comment by ArunYogi** [comment]
Fixed in version 1.0.3

**Comment by yatinmob** [comment]
is it merged with master @ArunYogi?

**Comment by ArunYogi** [comment]
yes

**Comment by puspendudas** [comment]
Unable to make payment during development. don't show any error. @ArunYogi
