### ISSUE TITLE
intent is null when using Freecharge

### ISSUE THREAD

**Issue by mtech2008** [ArunYogi/cordova-plugin-upi#7]
When freecharge app is used for payment after clickin gon pay button intent becomes null and gives error USER_CANCELED

**Comment by ArunYogi** [comment]
This apps works on design from NPCI, on how "UPI" supporting should consider the input and give response back. Not all the apps are giving correct response back on intent based transaction. So better check with your Bank API, whether transaction was successful or not, irrespective of response from UPI app
